# Generated by Django 3.1.5 on 2021-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_nick',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
