# Generated by Django 3.1.5 on 2021-01-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telechat', '0002_chat_user_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_nick',
        ),
    ]
